### GENERAL SETTINGS ###

plugins:
  - github-pages
  - jekyll-admin

# Site settings
title: ALEBAT
description: "ALEBAT"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#ffffff" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#ffffff" #"#33004D"
  link: "#292C37"
  link_hover: "#384452"
  footer_heading: "#292C37"
  footer_content: "#292C37"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  3d:
    output: true
    permalink: /3d/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: https://twitter.com/batbandage
  - title: tumblr
    url: https://battington.tumblr.com

email: alebat@alebatart.com